const fs = require('fs')
let file = fs.readFileSync('src/algorithms/binarySearch.ts', 'utf8')
let lines = file.split('\n')
lines[13] = lines[13].replace('8', '6')
lines[34] = lines[34].replace('8', '7')
lines[58] = lines[58].replace('8', '8')
lines[78] = lines[78].replace('8', '9')
lines[99] = lines[99].replace('10', '11')
fs.writeFileSync('src/algorithms/binarySearch.ts', lines.join('\n'))
